name: Langulus::TSIMDe CI
on: [push, pull_request] # Trigger on pushes to all branches and for all pull-requests

jobs:
  build:
    strategy:
      fail-fast: false # do not abort on a failed job
      matrix:
        os: [ubuntu-22.04, windows-latest]
        build: [Debug, Release]
        architecture: [x86, x64]
        feature: [
          [SSE, 16, '-msse', '/arch:SSE'],
          [SSE2, 16, '-msse2', '/arch:SSE2'],
          [SSE3, 16, '-msse3', '/arch:SSE3'],
          [SSSE3, 16, '-mssse3', '/arch:SSSE3'],
          [SSE4.1, 16, '-msse4.1', '/arch:SSE4.1'],
          [SSE4.2, 16, '-msse4.2', '/arch:SSE4.2'],
          [AVX, 32, '-mavx', '/arch:AVX'],
          [AVX2, 32, '-mavx2', '/arch:AVX2'],
          [AVX512, 64, '-mavx512', '/arch:AVX512']
        ]
        compiler: [g++, clang++, cl]
        exclude:
          - os: ubuntu-22.04
            compiler: cl
          - os: ubuntu-22.04
            architecture: x86
          - os: windows-latest
            compiler: g++
          - os: windows-latest
            compiler: clang++

        include:
          - os: ubuntu-22.04
            cmake_args: ""
          - os: windows-latest
            architecture: x86
            cmake_args: "-G \"Visual Studio 17 2022\" -A Win32"
          - os: windows-latest
            architecture: x64
            cmake_args: "-G \"Visual Studio 17 2022\" -A x64"

    name: "${{matrix.os}}-${{matrix.compiler}}-${{matrix.build}}-${{matrix.architecture}}-${{matrix.feature[0]}}"
    runs-on: ${{matrix.os}}
    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Configure Linux
        if: matrix.os == ubuntu-22.04
        run: >
          cmake
          -DCMAKE_CXX_COMPILER=${{matrix.compiler}}
          -S .
          -B out/${{matrix.name}}
          -DCMAKE_BUILD_TYPE=${{matrix.build}}
          ${{matrix.cmake_args}}
          -DCMAKE_CXX_FLAGS=${{matrix.feature[2]}}
          -DLANGULUS_ENABLE_SAFE_MODE=ON
          -DLANGULUS_ALIGNMENT=${{matrix.feature[1]}}
      - name: Configure Windows
        if: matrix.os == windows-latest
        run: >
          cmake
          -DCMAKE_CXX_COMPILER=${{matrix.compiler}}
          -S .
          -B out/${{matrix.name}}
          -DCMAKE_BUILD_TYPE=${{matrix.build}}
          ${{matrix.cmake_args}}
          -DCMAKE_CXX_FLAGS=${{matrix.feature[3]}}
          -DLANGULUS_ENABLE_SAFE_MODE=ON
          -DLANGULUS_ALIGNMENT=${{matrix.feature[1]}}
      - name: Build
        run: cmake --build out/${{matrix.name}} --config ${{matrix.build}}
      - name: Test
        run: cd out/${{matrix.name}} && ctest -V -C ${{matrix.build}}